<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RiivolutionIsoBuilder</AssemblyName>
    <RootNamespace>RiivolutionIsoBuilder</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Xml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="tools\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
